### ISSUE TITLE
申请SSL证书默认邮箱的建议

### ISSUE THREAD

**Issue by hapke24** [opentdp/tdp-cloud#60]
个人中心有设置邮箱的位置：
![1680202711849](https://user-images.githubusercontent.com/49407099/228937143-72283a00-b553-4309-80c3-f1369a672808.png)

申请SSL证书时可以自动把这个邮箱拿过来用，替换掉默认邮箱：

![1680202774635](https://user-images.githubusercontent.com/49407099/228937423-ff02106e-c392-4247-8cd7-73b35acc2852.png)

**Comment by rehiy** [comment]
这个已支持
