### ISSUE TITLE
docker升级到最新版本后容器异常退出

### ISSUE THREAD

**Issue by HanadaLee** [opentdp/tdp-cloud#64]
升级最新docker镜像后的日志：
[error.log](https://github.com/open-tdp/tdp-cloud/files/11218378/error.log)

以下为新旧镜像的具体信息（旧镜像是3周前的版本）
{"Containers":"N/A","CreatedAt":"2023-04-12 15:15:53 +0800 CST","CreatedSince":"22 hours ago","Digest":"\u003cnone\u003e","ID":"fe3afd0a2c39","Repository":"rehiy/tdp-cloud","SharedSize":"N/A","Size":"32.2MB","Tag":"latest","UniqueSize":"N/A","VirtualSize":"32.23MB"}
{"Containers":"N/A","CreatedAt":"2023-03-20 18:12:43 +0800 CST","CreatedSince":"3 weeks ago","Digest":"","ID":"5be625e46f34","Repository":"rehiy/tdp-cloud","SharedSize":"N/A","Size":"31.8MB","Tag":"\u003cnone\u003e","UniqueSize":"N/A","VirtualSize":"31.82MB"}

还原到备份数据库，使用旧镜像重新创建容器后服务正常

**Comment by rehiy** [comment]
这个应该是部分机器没有注册worker导致的，可以升级下数据库 `update machine set worker_id = NULL where worker_id = ''`

**Comment by HanadaLee** [comment]
我没有用tdp的worker，所以所有机器都没注册worker
docker容器在报错后会直接退出，能更新一下升级逻辑么，等下个版本再升级
