### ISSUE TITLE
子节点导入的时候报错

### ISSUE THREAD

**Issue by Calle-99** [opentdp/tdp-cloud#70]
Error 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`tdpcloud`.`machine`, CONSTRAINT `fk_vendor_machines` FOREIGN KEY (`vendor_id`) REFERENCES `vendor` (`id`))
![image](https://github.com/open-tdp/tdp-cloud/assets/72162184/919afdab-f1b0-496d-949e-3e03ad55ccc3)

**Comment by rehiy** [comment]
MySQL版问题，已经修复了。
