### ISSUE TITLE
阿里云轻量服务器读取不到

### ISSUE THREAD

**Issue by bestruirui** [opentdp/tdp-cloud#74]
![image](https://github.com/opentdp/tdp-cloud/assets/89796393/bd6c4b25-fc0b-4dd6-baf5-0d21c07c0ab5)
![image](https://github.com/opentdp/tdp-cloud/assets/89796393/0aee3e0a-0642-49b8-a53e-2b62c38c4a81)

**Comment by rehiy** [comment]
![image](https://github.com/opentdp/tdp-cloud/assets/8297757/9f0f305d-c268-4cea-989b-11e72aad7655)

测试是可以的，重新设置下密钥看看？
