### ISSUE TITLE
docker运行，重新启动后 登录web时 显示''登陆成功，密钥异常，请重新注册'', 然后就退出登录界面了

### ISSUE THREAD

**Issue by SlyLi** [opentdp/tdp-cloud#76]

**Comment by SlyLi** [comment]
> 有没有持久存储？

server.db 吗 还是其他什么？ 这个有

**Comment by rehiy** [comment]
可以看看生成的日志 docker logs 实例名

**Comment by SlyLi** [comment]
> 可以看看生成的日志 docker exec -it 实例 cat /var/log/tdp-cloud/日志名

有这个目录，但里面什么都没有

**Comment by rehiy** [comment]
没日志的话，目前无法确定准确的原因。是否有尝试过更换下服务器？如果没有重要的数据，也可以删除数据库后重置下。

**Comment by rehiy** [comment]
这个原因大概率是因为存储密钥不匹配导致的

**Comment by SlyLi** [comment]
> 这个情况大概率是因为存储密钥不匹配导致的，比如配置文件中的加密key被更换了

是不是重新启动后比对的密钥和之前的比对的不一样了 ？ 我删掉配置文件 重新docker-compose 然后修改密码登录，是正常的。docker stop tdp ，docker start tdp ，重启后还是有这个问题

**Comment by rehiy** [comment]
有个 yml 的配置文件，需要持久存储，你可以观察下，里面的存储key是否有变化

**Comment by rehiy** [comment]
理论上来讲，只有从配置文件读取不到存储key时，才会生成新的key，https://github.com/opentdp/tdp-cloud/blob/c6a2fcd56463ef468389c9dceda3f6370d86e05b/cmd/parse/server.go#L40

**Comment by SlyLi** [comment]
> 理论上来讲，只有从配置文件读取不到存储key时，才会生成新的key，
> 
> https://github.com/opentdp/tdp-cloud/blob/c6a2fcd56463ef468389c9dceda3f6370d86e05b/cmd/parse/server.go#L40

conf 目录下有个server.yml 里面这样
database:
    host: ""
    name: server.db
    option: ""
    passwd: ""
    type: sqlite
    user: ""
dataset:
    dir: /var/lib/tdp-cloud
logger:
    dir: /var/log/tdp-cloud
    level: info
server:
    listen: :7800

key应该存在这里吗？

**Comment by rehiy** [comment]
是这里的问题，你可以先手动配置一个32位长度以上的存储key，解决这个问题·
··
dataset:
    dir: var
    secret: 9R6GN7J229sdfsfwrwdswfwqrwewr123rtgdf
···

**Comment by SlyLi** [comment]
> 是这里的问题，你可以先手动配置一个32位长度以上的存储key，解决这个问题·
> 
> ```yaml
> database:
>     type: sqlite
>     name: server.db
> dataset:
>     dir: var
>     secret: 9R6GN7Jxxxxxxxxxxxxxxxxxxxxxx
> logger:
>     dir: .
>     level: info
>     target: stdout
> server:
>     listen: 127.0.0.1:7800
>     jwtkey: C1d31l5xxxxxxxxxxxxxxxxxxxxxxx
> ```

好的谢谢  反馈真快

**Comment by rehiy** [comment]
客气了，我先关闭iss，下个版本解决这个问题

**Comment by monlor** [comment]
docker部署的，这两个key都是存在的，也报错密钥异常

**Comment by monlor** [comment]
我是k8s，每次重启会配置文件是会丢失的，这样是有问题么

**Comment by rehiy** [comment]
需要确认下docker中是否使用了挂载的这个配置文件
